CREATE PROCEDURE SP_INSERT_CLIENTE
	
	@SWVM02CLI_ID INT, 
	@SWVM02NOMBRE VARCHAR(50), 
	@SWVM02DIRECCION VARCHAR(45), 
	@SWVM02CIRUC VARCHAR(13), 
	@SWVM02PROVINCIA VARCHAR(30), 
	@SWVM02CIUDAD VARCHAR(30), 
	@SWVM02TELEFONO1 VARCHAR(10), 
	@SWVM02TELEFONO2 VARCHAR(10), 
	@SWVM02EMAIL VARCHAR(80),
	@SWVM02CLAVE VARCHAR(250),  
	@SWVM02ESTADO VARCHAR(1), 
	@SWVM02FECHA_REGC DATETIME,
	@SWVM02FECHA_UPDATE DATETIME
	
AS 
	INSERT INTO SWVMMCLIENTE02 	
	VALUES(
	@SWVM02CLI_ID, 
	@SWVM02NOMBRE, 
	@SWVM02DIRECCION, 
	@SWVM02CIRUC, 
	@SWVM02PROVINCIA, 
	@SWVM02CIUDAD, 
	@SWVM02TELEFONO1, 
	@SWVM02TELEFONO2, 
	@SWVM02EMAIL,
	@SWVM02CLAVE,  
	@SWVM02ESTADO, 
	@SWVM02FECHA_REGC,
	@SWVM02FECHA_UPDATE)
	
	/*   **********************       */
	
	CREATE PROCEDURE SP_UPDATE_CLIENTE
	
    @SWVM02CLI_ID INT, 
	@SWVM02NOMBRE VARCHAR(50), 
	@SWVM02DIRECCION VARCHAR(45), 
	@SWVM02CIRUC VARCHAR(13), 
	@SWVM02PROVINCIA VARCHAR(30), 
	@SWVM02CIUDAD VARCHAR(30), 
	@SWVM02TELEFONO1 VARCHAR(10), 
	@SWVM02TELEFONO2 VARCHAR(10), 
	@SWVM02EMAIL VARCHAR(80),
	@SWVM02CLAVE VARCHAR(250),  
	@SWVM02ESTADO VARCHAR(1), 
	@SWVM02FECHA_UPDATE DATETIME
	
AS
		UPDATE SWVMMCLIENTE02
			SET			
			SWVM02NOMBRE= @SWVM02NOMBRE,
			SWVM02DIRECCION = @SWVM02DIRECCION , 
			SWVM02CIRUC = @SWVM02CIRUC, 
			SWVM02PROVINCIA = @SWVM02PROVINCIA, 
			SWVM02CIUDAD = @SWVM02CIUDAD , 
			SWVM02TELEFONO1 = @SWVM02TELEFONO1, 
			SWVM02TELEFONO2 = @SWVM02TELEFONO2 , 
			SWVM02EMAIL = @SWVM02EMAIL,
			SWVM02CLAVE = @SWVM02CLAVE,  
			SWVM02ESTADO = @SWVM02ESTADO, 
			SWVM02FECHA_UPDATE  = @SWVM02FECHA_UPDATE
			WHERE SWVM02CLI_ID=@SWVM02CLI_ID
			
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_CLIENTE
	@SWVM02CLI_ID INT,
	@ERROR VARCHAR (5) OUTPUT 	
AS
    DECLARE @ERROR_VAR int 
	DELETE FROM SWVMMCLIENTE02
		WHERE (SWVM02CLI_ID=@SWVM02CLI_ID)
	SELECT @ERROR_VAR = @@ERROR
	
	IF (@ERROR_VAR <> 0)
			SET @ERROR = 'ERROR'
	ELSE 
	        SET @ERROR = 'GRABO'
			