CREATE PROCEDURE SP_INSERT_USUARIO
	@SWVM08USER_ID INT,
	@SWVM08NOMBRE VARCHAR(50), 
	@SWVM08DEPARTAMENTO VARCHAR(30), 
	@SWVM08CARGO VARCHAR(15), 
	@SWVM08EMAIL VARCHAR(80), 
	@SWVM08CLAVE VARCHAR(250),
	@SWVM08ESTADO VARCHAR(1),
	@SWVM08FECHA_REGU DATETIME,
	@SWVM08FECHA_UPDATE DATETIME 
AS 
	INSERT INTO SWVMMUSUARIO08 
	VALUES
	(	@SWVM08USER_ID,
		@SWVM08NOMBRE, 
		@SWVM08DEPARTAMENTO, 
		@SWVM08CARGO, 
		@SWVM08EMAIL, 
		@SWVM08CLAVE,
		@SWVM08ESTADO,
		@SWVM08FECHA_REGU,
		@SWVM08FECHA_UPDATE) 
	
	/*   **********************       */
	
	CREATE PROCEDURE SP_UPDATE_USUARIO
	
	@SWVM08USER_ID INT,
	@SWVM08NOMBRE VARCHAR(50), 
	@SWVM08DEPARTAMENTO VARCHAR(30), 
	@SWVM08CARGO VARCHAR(15), 
	@SWVM08EMAIL VARCHAR(80), 
	@SWVM08CLAVE VARCHAR(250),
	@SWVM08ESTADO VARCHAR(1),	
	@SWVM08FECHA_UPDATE DATETIME 	
AS
		UPDATE SWVMMUSUARIO08
			SET			
			SWVM08NOMBRE=@SWVM08NOMBRE,
			SWVM08DEPARTAMENTO=@SWVM08DEPARTAMENTO,
			SWVM08CARGO=@SWVM08CARGO,
			SWVM08EMAIL=@SWVM08EMAIL, 			
			SWVM08CLAVE=@SWVM08CLAVE,
			SWVM08ESTADO=@SWVM08ESTADO, 			
			SWVM08FECHA_UPDATE=@SWVM08FECHA_UPDATE
			WHERE SWVM08USER_ID=@SWVM08USER_ID
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_USUARIO
	@SWVM08USER_ID INT
AS
	DELETE FROM SWVMMUSUARIO08
		WHERE (SWVM08USER_ID=@SWVM08USER_ID)
			