--                                                         
 -- 21 - abril - 2010
 -- ejecucion perfecta
 
 
CREATE TABLE SWVMMPROVEEDOR01(
SWVM01PROV_ID INTEGER NOT NULL PRIMARY KEY, 
SWVM01NOM_EMPRESA VARCHAR(50), 
SWVM01NOM_CONTACTO VARCHAR(50), 
SWVM01CARGO_CONTACTO VARCHAR(20), 
SWVM01RUC VARCHAR(13) UNIQUE, 
SWVM01DIRECCION VARCHAR(45), 
SWVM01TELEFONO1 VARCHAR(10), 
SWVM01TELEFONO2 VARCHAR(10), 
SWVM01PAIS VARCHAR(15), 
SWVM01PROVINCIA VARCHAR(30), 
SWVM01CIUDAD VARCHAR(30), 
SWVM01EMAIL VARCHAR(80),
SWVM01CLAVE VARCHAR(250),
SWVM01ESTADO VARCHAR(1), 
SWVM01FECHA_REGP DATETIME,
SWVM01FECHA_UPDATE DATETIME); 

CREATE TABLE SWVMMCLIENTE02(
SWVM02CLI_ID INTEGER NOT NULL PRIMARY KEY, 
SWVM02NOMBRE VARCHAR(50), 
SWVM02DIRECCION VARCHAR(45), 
SWVM02CIRUC VARCHAR(13) UNIQUE, 
SWVM02PROVINCIA VARCHAR(30), 
SWVM02CIUDAD VARCHAR(30), 
SWVM02TELEFONO1 VARCHAR(10), 
SWVM02TELEFONO2 VARCHAR(10), 
SWVM02EMAIL VARCHAR(80),
SWVM02CLAVE VARCHAR(250),  
SWVM02ESTADO VARCHAR(1), 
SWVM02FECHA_REGC DATETIME,
SWVM02FECHA_UPDATE DATETIME); 

CREATE TABLE SWVMMCATEGORIA03(
SWVM03CATE_ID INTEGER NOT NULL PRIMARY KEY, 
SWVM03CATE_NOMBRE VARCHAR(30), 
SWVM03DESCRIPCION VARCHAR(120), 
SWVM03IMAGENAME VARCHAR(60),
SWVM03FECHA_REGCAT DATETIME,
SWVM03FECHA_UPDATE DATETIME); 

CREATE TABLE SWVMMPRODUCTO04(
SWVM04PROD_ID INTEGER NOT NULL, 
SWVM04CATE_ID INTEGER NOT NULL, 
SWVM04PROD_NOMBRE VARCHAR(30), 
SWVM04PRECIO "MONEY", 
SWVM04STOCK INTEGER, 
SWVM04DESCRIPCION VARCHAR(500), 
SWVM04URL VARCHAR(120), 
SWVM04SIZE VARCHAR(10), 
SWVM04IMAGENAME VARCHAR(60), 
SWVM04PROV_ID INTEGER NOT NULL,
SWVM04FECHA_REGPRO DATETIME,
SWVM04FECHA_UPDATE DATETIME,
FOREIGN KEY (SWVM04CATE_ID)
REFERENCES SWVMMCATEGORIA03(SWVM03CATE_ID),
FOREIGN KEY (SWVM04PROV_ID)
REFERENCES SWVMMPROVEEDOR01(SWVM01PROV_ID),
CONSTRAINT SWVM04PID_CID_PROVID PRIMARY KEY(SWVM04PROD_ID,SWVM04CATE_ID,SWVM04PROV_ID)); 

CREATE TABLE SWVMEPARAMETRO05(
SWVM05EMPRESA_ID INTEGER NOT NULL PRIMARY KEY, 
SWVM05NOM_EMPRESA VARCHAR(30),  
SWVM05P_IVA "MONEY", 
SWVM05FECHA_REGPARA DATETIME,
SWVM05FECHA_UPDATE DATETIME);


CREATE TABLE SWVMCCAB_COTI06(
SWVM06COTI_ID INTEGER NOT NULL PRIMARY KEY, 
SWVM06FECHA DATETIME,
SWVM06CLI_ID INTEGER NOT NULL, 
SWVM06TOTAL "MONEY",
SWVM06ESTADO VARCHAR(1),
SWVM06FECHA_UPDATE DATETIME,
FOREIGN KEY (SWVM06CLI_ID) REFERENCES SWVMMCLIENTE02(SWVM02CLI_ID)); 

CREATE TABLE SWVMDDET_COTI07(
SWVM07COTI_ID INTEGER NOT NULL, 
SWVM07PROD_ID INTEGER NOT NULL,
SWVM07CATE_ID INTEGER NOT NULL,
SWVM07CANTIDAD INTEGER, 
SWVM07PRECIO "MONEY", 
SWVM07SUBTOTAL "MONEY", 
SWVM07IVA "MONEY", 
SWVM07PROV_ID INTEGER NOT NULL,
FOREIGN KEY (SWVM07COTI_ID) 
REFERENCES SWVMCCAB_COTI06(SWVM06COTI_ID),
FOREIGN KEY (SWVM07PROD_ID,SWVM07CATE_ID,SWVM07PROV_ID) 
REFERENCES SWVMMPRODUCTO04(SWVM04PROD_ID,SWVM04CATE_ID,SWVM04PROV_ID)); 

CREATE TABLE SWVMMUSUARIO08(
SWVM08USER_ID INTEGER NOT NULL PRIMARY KEY, 
SWVM08NOMBRE VARCHAR(50), 
SWVM08DEPARTAMENTO VARCHAR(30), 
SWVM08CARGO VARCHAR(15), 
SWVM08EMAIL VARCHAR(80), 
SWVM08CLAVE VARCHAR(250),
SWVM08ESTADO VARCHAR(1),
SWVM08FECHA_REGU DATETIME,
SWVM08FECHA_UPDATE DATETIME ); 

CREATE TABLE SWVMTAUDITORIA09(
SWVM09AUD_ID INTEGER NOT NULL PRIMARY KEY, 
SWVM09USER_ID VARCHAR(3), 
SWVM09NOMTABLA_ID VARCHAR(4), 
SWVM09FECHA_AU DATETIME); 

CREATE TABLE SWVMHPAGINA10(
SWVM10PAG_ID INTEGER NOT NULL PRIMARY KEY,
SWVM10CONTENT "TEXT",
SWVM10NOMBRE VARCHAR(30),
SWVM10DESCRIPCION VARCHAR(80),
SWVM10FECHAR DATETIME,
SWVM10FECHAU DATETIME,
SWVM10USER_ID INTEGER NOT NULL,
FOREIGN KEY (SWVM10USER_ID) REFERENCES SWVMMUSUARIO08(SWVM08USER_ID))
