INSERT INTO SWVMHPAGINA10
VALUES (
1,
'
<table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td style="text-align: left;" colspan="4">
            <br>
                <span><span style="font-size: 24pt;"><span style="color: rgb(0, 0, 0);">&nbsp;Bienvenidos</span> <span style="color: rgb(255, 255, 153); font-size: 16pt;">
                    <span style="color: rgb(0, 0, 0);">a</span> <span style="color: rgb(255, 153, 0);">Vivero</span><span style="color: rgb(255, 153, 51);">Market.. <span style="font-size: 14pt; color: rgb(255, 255, 255);">vida para
                            tu hogar.</span></span></span></span></span></td>
            <td style="width: 121px;">
            <br></td>
        </tr>
        <tr>
            <td style="width: 147px; height: 2px;">
            <br></td>
            <td style="height: 2px;">
            <br></td>
            <td style="width: 224px; height: 2px;">
            <br></td>
            <td style="width: 898px; height: 2px;">
            <br></td>
            <td style="width: 121px; height: 2px;">
            <br></td>
        </tr>
        <tr>
            <td style="width: 147px;">
            <br></td>
            <td style="vertical-align: top;">
                <img class="corner iradius16" src="http://viveromarket.com/images/img_bienvenida.jpg" style="width: 271px; height: 293px;"></td>
            <td style="width: 224px;">
            <br></td>
            <td rowspan="2" style="vertical-align: super; width: 898px; text-align: left;">
                <table width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tbody><tr>
                        <td rowspan="5" style="background-position: 98% top; background-image: url(&quot;images/bghome.jpg&quot;); background-repeat: no-repeat; text-align: justify;">
                            <span style="font-size: 11pt;">ViveroMarket es una empresa que en poco tiempo
                                ha tenido un gran crecimiento gracias a la aceptación y recomendación de nuestros
                                clientes.</span>
                                <br>
                                <br>
                                 <span style="font-size: 11pt;">Actualmente contamos con tres sucursales  con una gran variedad de plantas
                                  y macetas para todos los gustos.</span><br>
                                <br>
                                   <span style="font-size: 11pt;">ViveroMarket además de contar con la mejor calidad de plantas de Aguascalientes cuenta con otros servicios como diseños por computadora, fumigaciones y fertilizaciones, pasto en rollo, etc.</span><br>
                                <br><span style="font-size: 11pt;">Recuerde, ViveroMarket con sus servicios le transmite, confort, tranquilidad, funcionalidad, exclusividad y el respaldo de una empresa seria y comprometida con nuestra naturaleza.</span></td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                    </tr>
                </tbody></table>
            </td>
            <td style="width: 121px;">
            <br></td>
        </tr>
        <tr>
            <td style="width: 147px; height: 1px;">
            <br></td>
            <td style="height: 1px;">
            <br></td>
            <td style="width: 224px; height: 1px;">
            <br></td>
            <td style="width: 121px; height: 1px;">
            <br></td>
        </tr>
        <tr>
            <td style="width: 147px;">
            <br></td>
            <td style="text-align: justify;" colspan="">
                <span style="font-size: 11pt;">Mediante este Sitio Web usted tiene la oportunidad de cotizar nuestros productos en línea, obteniendo
                    así los mejores precios del Mercado.</span></td>
            <td style="width: 224px;">
            <br></td>
            <td style="width: 898px; text-align: left;">
                &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;
                <img class="corner iradius16" src="http://viveromarket.com/images/img_macetas.jpg" style="width: 280px; height: 91px;"></td>
            <td style="width: 121px;">
            <br></td>
        </tr>
        <tr>
            <td style="width: 147px; height: 3px;">
            <br></td>
            <td style="height: 3px;">
            <br></td>
            <td style="width: 224px; height: 3px;">
            <br></td>
            <td style="width: 898px; height: 3px;">
            <br></td>
            <td style="width: 121px; height: 3px;">
            <br></td>
        </tr>
        <tr>
            <td style="width: 147px;">
            <br></td>
            <td colspan="3" style="vertical-align: top;">
                <span style="font-size: 11pt; vertical-align: top;">&nbsp;<img class="corner iradius16" src="http://viveromarket.com/images/img_viveros.jpg" style="vertical-align: super; width: 271px; height: 93px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <img class="corner iradius16" src="http://viveromarket.com/images/img_diseno.jpg" style="vertical-align: top; width: 277px; height: 88px;"></span></td>
            <td style="width: 121px;">
            <br></td>
        </tr>
    </tbody></table>
',
'HOME', 'Página Principal de Vivero Market', GETDATE(), GETDATE(), 1)

INSERT INTO SWVMHPAGINA10
VALUES (
2,
'
<table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tbody><tr>
            <td style="width: 16px; height: 20px;">
            </td>
            <td style="height: 20px;">
            </td>
            <td style="width: 14px; height: 20px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px;">
            </td>
            <td>
                <span style="font-size: 14pt;">Quienes Somos</span></td>
            <td style="width: 14px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 5px;">
            </td>
            <td style="border-bottom-color: rgb(136, 204, 85); height: 5px; border-bottom-style: solid;">
            </td>
            <td style="width: 14px; height: 5px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 10px;">
            </td>
            <td style="height: 10px;">
            </td>
            <td style="width: 14px; height: 10px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px;">
            </td>
            <td style="text-align: justify;">
                <span style="font-size: 11pt;">Somos una empresa dedicada a la comercialización de plantas,
                    ViveroMarket es nuestro nombre comercia utilizado para establecer presencia en Internet.<br>
                    <br>
                    La Empresa Vivero Cía. Ltda, fue creada y registrada en el año de 1984 contamos
                    con local propio, más desde mucho antes formamos parte de una tradición familiar,
                    que hereda habilidades y amor por la naturaleza a nuestras generaciones.<br>
                </span>
            </td>
            <td style="width: 14px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 25px;">
            </td>
            <td style="height: 25px;">
            </td>
            <td style="width: 14px; height: 25px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px;">
            </td>
            <td>
                <span style="font-size: 14pt;">Misión</span></td>
            <td style="width: 14px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 5px;">
            </td>
            <td style="border-bottom-color: rgb(255, 187, 85); height: 5px; border-bottom-style: solid;">
            </td>
            <td style="width: 14px; height: 5px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 10px;">
            </td>
            <td style="height: 10px;">
            </td>
            <td style="width: 14px; height: 10px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px;">
            </td>
            <td style="text-align: justify;">
                <span style="font-size: 11pt;">Colaborar en el cuidado del medio ambiente, desarrollando
                    espacios verdes armónicos, manteniendo y cultivando especies botánicas, compartiendo
                    conocimientos y experiencias con personas que valoran y disfrutan la naturaleza,
                    teniendo como objetivo común mejorar la calidad de vida de quienes habitamos la
                    tierra protegiendo y preservando el medio ambiente.<br>
                    <br>
                    Todo esto con el soporte del personal con la más alta experiencia en plantas, para
                    satisfacer a nuestros clientes.</span></td>
            <td style="width: 14px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 25px;">
            </td>
            <td style="height: 25px;">
            </td>
            <td style="width: 14px; height: 25px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px;">
            </td>
            <td>
                <span style="font-size: 14pt;">Visión</span></td>
            <td style="width: 14px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px;">
            </td>
            <td style="border-bottom-color: rgb(238, 238, 102); border-bottom-style: solid;">
                <span style="font-size: 14pt;"></span>
            </td>
            <td style="width: 14px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 10px;">
            </td>
            <td style="height: 10px;">
            </td>
            <td style="width: 14px; height: 10px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px;">
            </td>
            <td style="text-align: justify;">
                <span style="font-size: 11pt;">Somos una Empresa activa y competitiva, económicamente
                    rentable y ambientalmente sostenible, con un grupo humano que trabaja en un entorno
                    agradable, mejorando su nivel de vida, el de sus familias y el de los clientes.<br>
                    <br>
                    Nuestra empresa tiene como visión llegar a ser la empresa líder en el país en la
                    venta y asesoría de plantas mediante estrategias que garanticen el desarrollo sostenible.</span></td>
            <td style="width: 14px;">
            </td>
        </tr>
        <tr>
            <td style="width: 16px; height: 10px;">
            </td>
            <td style="height: 10px;">
            </td>
            <td style="width: 14px; height: 10px;">
            </td>
        </tr>
    </tbody></table>
',
'SOMOS', 'Página con detalles de la Empresa', GETDATE(), GETDATE(), 1)

INSERT INTO SWVMHPAGINA10 
VALUES (
3, 
'
<table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tbody><tr>
            <td style="width: 17px; height: 10px;">
            <br></td>
            <td colspan="3" style="height: 10px;">
            <br></td>
            <td style="width: 20px; height: 10px;">
            <br></td>
        </tr>
        <tr>
            <td style="width: 17px;">
            <br></td>
            <td colspan="3">
                <span style="font-size: 14pt;">Nuestros Servicios</span></td>
            <td style="width: 20px; font-size: 9pt;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px; height: 3px;">
            <br></td>
            <td colspan="3" style="border-bottom: thick solid rgb(255, 187, 85); height: 3px;">
            <br></td>
            <td style="width: 20px; height: 3px;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px; height: 10px;">
            <br></td>
            <td style="width: 311px; height: 10px;">
            <br></td>
            <td style="width: 20px; height: 10px;">
            <br></td>
            <td style="width: 340px; height: 10px;">
            <br></td>
            <td style="width: 20px; height: 10px;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px; height: 14px;">
            <br></td>
            <td colspan="3" style="height: 14px;">
                <span style="color: rgb(136, 204, 85);"><strong>Servicios de Jardinería</strong></span></td>
            <td style="width: 20px; height: 14px;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px; height: 14px;">
            <br></td>
            <td colspan="2" style="vertical-align: top; height: 14px;">
                <br>
                <ul>
                    <li>Proyección y Diseño de Jardines</li><li>Creación de Parques y Jardines</li><li>Acondicionamiento y Mantenimiento de áreas verdes.</li><li>Creación y conservación de campos de fútbol, campos de golf, áreas recreativas y
                        áreas verdes en General.</li><li>Poda de árboles de gran porte</li><li>Diferentes altura Poda y cirugías arbóreas y arbustivas</li><li>Tratamientos fitosanitarios</li></ul>
            </td>
            <td style="width: 340px; height: 14px; text-align: center;">
                <img class="reflex" src="http://viveromarket.com/images/jardin.jpg" style="width: 214px; height: 166px;"></td>
            <td style="width: 20px; height: 14px;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px; height: 14px;">
            <br></td>
            <td style="width: 311px; height: 14px;">
            <br></td>
            <td style="width: 20px; height: 14px;">
            <br></td>
            <td style="width: 340px; height: 14px;">
            <br></td>
            <td style="width: 20px; height: 14px;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px;">
            <br></td>
            <td style="width: 311px;">
                <strong><span style="color: rgb(136, 204, 85);">División Diseño</span></strong></td>
            <td style="width: 20px;">
            <br></td>
            <td style="width: 340px;">
            <br></td>
            <td style="width: 20px;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px;">
            <br></td>
            <td style="width: 311px;">
                <ul>
                    <li style="margin-top: 0pt; margin-bottom: 0pt;">Automatizado y manual para residencias,
                        comercios, industrias, Campos deportivos y demás áreas verdes.</li>
                    <li style="margin-top: 0pt; margin-bottom: 0pt;"><b><span style="font-size: 9pt;">Riego
                        municipal</span></b><br>
                        Jardines públicos, Parques,y&nbsp; áreas ajardinadas&nbsp;</li>
                    <li style="margin-top: 0pt; margin-bottom: 0pt;"><b><span style="font-size: 9pt;">Riego
                        de Campos Deportivos</span></b><br>
                        Complejos deportivos, o campos de césped natural o artificial</li>
                    <li style="margin-top: 0pt; margin-bottom: 0pt;"><b><span style="font-size: 9pt;">Riego
                        de Campos de Golf</span></b><br>
                        Nuevos campos y renovaciones.</li>
                    <li style="margin-top: 0pt; margin-bottom: 0pt;"><b><span style="font-size: 9pt;">Riego
                        de Cultivos Agrícolas</span></b><br>
                        Viveros, Ruego Agrícola.</li>
                </ul>
            </td>
            <td style="width: 20px;">
            <br></td>
            <td style="width: 340px; text-align: center;">
                <img class="reflex" src="http://viveromarket.com/images/irrigacion.jpg" style="width: 214px; height: 166px;"></td>
            <td style="width: 20px;">
            <br></td>
        </tr>
        <tr style="font-size: 9pt;">
            <td style="width: 17px;">
            <br></td>
            <td style="width: 311px;">
            <br></td>
            <td style="width: 20px;">
            <br></td>
            <td style="width: 340px;">
            <br></td>
            <td style="width: 20px;">
            <br></td>
        </tr>
    </tbody></table>

',
'SERVICIOS', 'Muestra los servicios que presta ViveroMarket', GETDATE(), GETDATE(), 1)