INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (1, 1, 'GIRASOL',1.00, 100, 
                      'SE CULTIVA PARA LA OBTENCION DEL ACEITE Y EN MENOR ESCALA PARA CONSUMIR LAS SEMILLAS',
                       NULL, 2.00, '1.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (2, 1, 'CLAVEL',1.00, 100, 
                      'SE LA CULTIVA POR LO HERMOSO DE SUS FLORES QUE SE HACEN DOBLES Y ADQUIEREN COLORES MUY DIVERSOS',
                       NULL, 0.02, '2.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (3, 1, 'AZUCENA',0.05, 100, 
                      'SUS ESPECIES Y VARIEDADES SE DIFERENCIAN EN EL COLOR DE LAS FLORES Y SE CULTIVAN PARA ADORNO EN LOS JARDINES',
                       NULL, 0.05, '3.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (4, 1, 'LIRIO',0.50, 100, 
                      'FRUTO CAPSULAR CON MUCHAS SEMILLAS Y RIZOMA RASTRERO Y NUDOSO',
                       NULL, 0.05, '4.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (5, 1, 'GERANIO', 0.50, 100, 
                      'HAY VARIAS ESPECIES QUE SE DISTINGUEN POR EL TAMAÑO DE LAS HOJAS VELLOSAS O NO Y MAS O MENOS RECORTADAS Y SOBRE TODO POR EL OLOR Y COLORACION DE LAS FLORES',
                       NULL, 0.05, '5.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (6, 1, 'ROSAS', 1.00, 100, 
                      'FLOR DEL ROSAL NOTABL, LA SUAVIDAD DE SU FRAGANCIA Y SU COLOR GENERALMENTE ENCARNADO POCO SUBIDO',
                       NULL, 1.00, '6.JPG',1 , GETDATE(),GETDATE())




INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (7, 1, 'MARGARITA', 0.50, 100, 
                     'PLANTA HERBACEA CON HOJAS CASI ABRAZADORAS OBLONGAS FESTONEADAS HENDIDAS EN LA BASE Y FLORES TERMINALES DE CENTRO AMARILLO Y COROLA BLANCA',
                       NULL, 0.05, '7.JPG',1 , GETDATE(),GETDATE())




INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (8, 1, 'PETUNIA', 0.05, 100, 
                      'PLANTAS CON LAS HOJAS AOVADAS Y ENTERAS Y LAS FLORES EN FORMA DE EMBUDO GRANDES OLOROSAS Y DE DIVERSOS COLORES',
                       NULL, 0.05, '8.JPG',1 , GETDATE(),GETDATE())




INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (9, 1, 'TULIPAN', 0.50, 100, 
                      'FLOR UNICA EN LO ALTO DEL ESCAPO GRANDE GLOBOSA DE SEIS PETALOS DE HERMOSOS COLORES E INODORA Y FRUTO CAPSULAR CON MUCHAS SEMILLAS',
                       NULL, 0.08, '9.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (10, 1, 'CRISANTO', 0.60, 100, 
                      'SON VERDES POR ENCIMA Y BLANQUECINAS POR EL ENVES Y FLORES ABUNDANTES DE COLORES VARIADOS PERO FRECUENTEMENTE MORADAS SE CULTIVAN EN LOS JARDINES DONDE FLORECE DURANTE EL OTOÑO',
                       NULL, 0.20, '10.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (11, 1, 'ORQUIDEA', 0.10, 100, 
                      'LAS FLORES SE ABREN SOBRE TALLOS LLAMADOS PEDICELOS COMO CUALQUIER OTRA FLOR DURANTE EL DESARROLLO EL PEDICELO GIRA 180° DE FORMA QUE LA FLOR MADURA QUEDA BOCA ABAJO',
                       NULL, 0.05, '11.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (12, 1, 'VIOLETA', 0.50, 100, 
                      'FLORES CASI SIEMPRE DE COLOR MORADO CLARO Y A VECES BLANCAS Y DE SUAVISIMO OLOR',
                       NULL, 0.08, '12.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (13, 1, 'GARDENIA', 0.50, 100, 
                      'HOJAS LISAS GRANDES OVALADAS AGUDAS POR AMBOS EXTREMOS Y DE COLOR VERDE BRILLANTE DE PETALOS GRUESOS BLANCAS Y OLOROSAS Y FRUTA DE BAYA DE PULPA AMARILLENTA',
                       NULL, 2.00, '13.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (14, 1, 'ALHELI', 0.10, 100, 
                      'HOJAS LISAS CON FLORES DE COLRES  VIOLETAS BRILLANTES DE PETALOS GRUESOS',
                       NULL, 0.05, '14.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (15, 1, 'AMAPOLA', 0.50, 100, 
                      'FLOR COLOR  BLANCA BRILLANTES DE PETALOS GRANDES CON SEMILLAS AMARILLAS',
                       NULL, 0.05, '15.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (16, 1, 'CLAVELINA', 0.20, 100, 
                      'COLOR DE PETALOS PUNTIAGUDOS DE COLORES PURPURA',
                       NULL, 0.05, '16.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (17, 1, ' DELPHINIUM', 0.20, 100, 
                      'FLORES DE COLORES MORADOS CON PETALOS PEQUEÑOS Y SEMILLAS BLANCAS',
                       NULL, 0.05, '17.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (18, 1, 'AMAPOLA', 0.50, 100, 
                      'FLOR HERMOSA CON PETALOS COLOR VIOLETA Y BLANCO PETALOS GURESOS Y GRANDES',
                       NULL, 0.08, '18.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (19, 1, 'LOTO', 0.20, 100, 
                      'FLOR CON PETALOS PEQUEÑOS DE COLOR ROJO CLARO',
                       NULL, 0.05, '19.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (20, 1, ' FRITILARIA', 0.50, 100, 
                      'FLOR CON PETALOS GRANDES DE COLOR CAFFE AMARILLO Y NEGRO',
                       NULL, 0.05, '20.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (21, 1, ' GLADIOLO', 0.50, 100, 
                      'FLOR HERMOSA CON PETALOS GRANDES Y GRUESOS DE COLOR BLANCO CON PURPURA Y AMARILLO',
                       NULL, 0.08, '21.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (22, 1, ' HORTENSIA ', 0.50, 100, 
                      'LA HORTENSIA DESTACA FUNDAMENTALMENTE POR SUS INFLORESCENCIAS, FORMADAS POR CAPÍTULOS CON FLORES BLANCAS MUY PEQUEÑAS RODEADAS DE BRÁCTEAS BLANCAS, FUCSIAS, ROSADAS O AZULES QUE SON LAS QUE PROPIAMENTE PROPORCIONAN EL COLOR DE LA INFLORESCENCIA.',
                       NULL, 0.05, '22.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (23, 1, ' JACINTO ', 0.20, 100, 
                      'FLOR HERMOSA CON PETALOS GRUESOS PERO PERQUEÑOS DE COLOR PURPURA CLARO ',
                       NULL, 0.05, '23.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (24, 1, ' MAGNOLIA', 0.20, 100, 
                      'FLOR DE COLOR BLANCA CON PETALOS GRUESOS Y GRANDES',
                       NULL, 0.03, '24.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (25, 1, ' NARCISOS', 0.05, 100, 
                      'FLOR DE COLOR AMARILLO CON SEMILLA DE COLOR ROJISO PETALOS GRUESOS Y GRANDES',
                       NULL, 0.05, '25.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (26, 1, ' ROSABLANCA', 0.50, 100, 
                      'ESTA ROSA TIENE DIFERENTES COLORES DE PETALOS  ESTOS SON BLANCOS PERO SIEMPRE CON TONOS DE OTROS COLORES',
                       NULL, 0.05, '26.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (27, 1, ' ROSAMALVA', 0.20, 100, 
                      'FLOR BRILLANTES CON PETALOS GRUESOS Y GRANDES DE COLOR VIOLETA CLARO',
                       NULL, 0.03, '27.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (28, 1, ' VINCA', 0.20, 100, 
                      'FLOR GRANDES DE PETALOS GRUESOS COLOR VIOLETA OSCURO  Y SEMILLA BLANCA',
                       NULL, 0.05, '28.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (1, 2, 'ORTIGA', 0.50, 100, 
                      'ES CARACTERISTICA DE LAS ZONAS TEMPLADAS DEL MUNDO SUS FLORES CRECEN EN UNAS ESPIGAS Y SECRETAN 
                       UN LIQUIDO URENTE TAMBIEN ES UN ESTIMULANTE DEL SISTEMA DIGESTIVO',
                       NULL, 0.50, '1.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (2, 2, 'LLANTEN', 0.30, 100, 
                      'CRECE EN TERRENO BALDIOS COMO UNA MALESA COMUN CONOCIDA POR SUS PROPIEDADES CURATIVAS',
                       NULL, 0.40, '2.JPG',1 , GETDATE(),GETDATE())
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (3, 2, 'CANELA', 0.20, 100, 
                      'CULTIVO EN LA MAYOR PARTE DE LAS REGIONES TROPICALES CALIDAD Y HUMEDAS',
                       NULL, 0.20, '3.JPG',1 , GETDATE(),GETDATE())
					   
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (4, 2, 'CEDRON', 0.30, 100, 
                      'ES UTILIZADO EN PERFUMERIA Y MEDICINA COMO SEDANTE ESTOMATICO Y ANTIESPASMODICO DE COLOR VERDE PALIDO',
                       NULL, 3.00, '4.JPG',1 , GETDATE(),GETDATE())
					   
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (5, 2, 'EUCALIPTO', 0.25, 100, 
                      'CONOCIDOS COMO MADERA DE SANGRE TAMBIEN SIRVE COMO FUENTE DE LA QUINA DE BOTANYBAY',
                       NULL, 0.30, '5.JPG',1 , GETDATE(),GETDATE())
					   
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (6, 2, 'AMARGON', 0.25, 100, 
                      'ACTUA EN LA PARTE PRINCIPAL DEL ORGANISM HUMANO SANGRE PORQUE AUMENTA LOS GLOBULOS ROJOS ',
                       NULL, 0.15, '6.JPG',1 , GETDATE(),GETDATE())
					   

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (7, 2, 'ANIS', 0.15, 100, 
                      'SU SEMILLA ES UTILIZADA EN ELABORACION DE LICORES Y EN MEDICINA COMO ESTIMULANTE ',
                       NULL, 0.05, '7.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (8, 2, 'APIO', 0.20, 100, 
                      'SON CONSUMIDOS CRUDOS EN ENSALADAS SUS SEMILLAS SON UTILIZADAS COMO SEDANTES',
                       NULL, 0.15, '8.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (9, 2, 'MANZANILLA', 0.10, 100, 
                      'ES UTILIZA EN MEDICINA COMO UNA INFUSION PAR4A LOS NERVIOS , INSOMIOS, REDUCE LAS INFLAMACIONES DEL APARATO DIGESTIVO',
                       NULL, 0.15, '9.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (10, 2, 'MATICO', 0.10, 100, 
                      'SUS HOJAS SON UTILIZADAS EN MEDICINA COMO UN TONICO ESTIMULANTE Y DIURETICO SIRVEN PARA TRATAR ULCERAS ESTOMACALE DIFERENTES TIPOS DE HEMORRAGIAS INTERNAS ',
                       NULL, 0.15, '10.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (11, 2, 'MENTA', 0.15, 100, 
                      'SON UTILIZADAS EN MEDICINA COMO UN ANTIPASMÓDICO, ESTIMULANTE ESTOMACAL, BACTERIOSTÁTICO Y COMO ESENCIA UTILIZADA EN LICORERIA',
                       NULL, 0.10, '11.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (12, 2, 'ROMERO', 0.20, 100, 
                      'SUS HOJAS SON UTILIZADAS COMO CONDIMENTO Y FUENTE DE UN ACEITE VOLÁTIL CUAL ES  UTILIZADO EN MEDICINA COMO ESTIMULAANTE Y TAMBIEN EN PERFUMERIA',
                       NULL, 0.15, '12.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (13, 2, 'RUDA', 0.15, 100, 
                      'PLANTA PARA DIFERENTE TIPO DE LIMPIA PARA PERSONAS',
                       NULL, 0.15, '13.JPG',1 , GETDATE(),GETDATE())






INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (14, 2, 'UÑA DE GATO', 0.20, 100, 
                      'ESTA PLANTA MEDICINAL SE USA PARA DIFERENTES TIPOS DE SANACIONES Y PARA LIMPIAR LA SANGRE DE IMPUREZAS',
                       NULL, 0.10, '14.JPG',1 , GETDATE(),GETDATE())




INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (15, 2, 'PAICO', 0.10, 100, 
                      'PLANTA MEDICINAL DIFERENTES INFUSIONES PARA FORTALECER EL CUERPO',
                       NULL, 0.15, '15.JPG',1 , GETDATE(),GETDATE())






INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (16, 2, 'VALERIANA', 0.10, 100, 
                      'LA INFUSION DE SUS  RAICES CARNOSAS SON RECOMENDADAS PARA EL ASMA NERVIOSO Y COMO UN FORTALECEDOR Y REGULADOR DE LOS LATIDOS CARDIACOS  ',
                       NULL, 0.15, '16.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (17, 2, 'OREGANO', 0.15, 100, 
                      'ESTA PLANTA SIRVE PARA INFUSIONES QUE SON RECOMENDADAS PARA LOS GASES GASTRICOS DEL CUERPO',
                       NULL, 0.05, '17.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (18, 2, 'SABILA', 0.45, 100, 
                      'EL GEL DE ALOE DE ESTA PLANTA ES UTILIZADA PARA LA CURACION DE HERIDAS, QUEMADURAS, LESSIONES EPIDÉRMICAS Y REDUCE EL DOLOR',
                       NULL, 0.15, '18.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (19, 2, 'MALVA', 0.25, 100, 
                      'NOMBRE DE UNA FAMILIA DE PLANTAS FORMADOS POR 100 GENEROS Y 2000 ESPECIES FUNDAMENTALMENTE ARBOLES Y ARBUSTOS ',
                       NULL, 0.15, '19.JPG',1 , GETDATE(),GETDATE())






INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (20, 2, 'CHIQUIRAGUA', 0.20, 100, 
                      'ES UTILIZADA EN LA MEDICINA COMO UN TONICO, ALIVIA LA TOS FUERTE, LA IRRITACION DE LOS RIÑONES, AYUDA EN LOS PROBLEMAS HEPATICOS Y AUMENTA LA PRODUCCION DE LA BILIS',
                       NULL, 0.25, '20.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (21, 2, 'QUINA ', 0.10, 100, 
                      'LA CORTEZA DE LA QUINA TIENE PROPIEDADES MEDICINALES DE LA CUAL SE EXTRAE LA QUININA',
                       NULL, 0.15, '21.JPG',1 , GETDATE(),GETDATE())




INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (22, 2, 'COLA DE CABALLO', 0.30, 100, 
                      'ES UTILIZADA COMO INFUSION DIURÉTICA, ES EFICAZ EN EL TRATAMIENTO DE HEMORRAGIAS  Y ULCERACIONES ',
                       NULL, 0.15, '22.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (1, 3, 'NARANJA', 4.10, 100, 
                      'NOMBRE DE CITRICO ESTE FRUTO ES UN HESPERIDIO QUE ES UNA VARIANTE DE LA BAYA CUBIERTA POR UN EXOCARPO O CÁSCARA DE COLOR
                        ANARANJADO EL CUAL CONTIENE ACEITES ESENCIALES',
                       NULL, 1.60, '1.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (2, 3, 'MANZANA', 3.25, 100, 
                      'EL MANZANO ES UN ARBOL CADUCIFOLIO DISTRIBUIDO SOBRE TODAS LAS REGIONES TEMPLADAS EL COLOR DE LA PIEL VA DESDE EL VERDE HASTA
                      EL ROJO MUY OSCURO',
                       NULL, 0.80, '2.JPG',1 , GETDATE(),GETDATE())
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (3, 3, 'MANDARINA', 4.30, 100, 
                      'DE COLOR AMARILLO ROJISO LAS FLORES SON BLANCAS NATIVO DEL SURESTE ASIATICO TIENE UN VALOR NUTRITIVO MUY SIMILAR AL DE LA 
                       NARANJA PERO ES MAS FRAGIL Y MAS EXPUESTO A SUFRIR DAÑOS DURANTE SU MANIPULACION',
                       NULL, 0.80, '3.JPG',1 , GETDATE(),GETDATE())
					   
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (4, 3, 'DURAZNO', 7.30, 100, 
                      'ARBOL QUE LOS BOTANICOS CONSIDERAN QUE SON NATIVOS DE CHINA Y SE CULTIVAN EN TODAS LAS REGIONES TEMPLADAS
                         Y SUBTROPICALES DEL MUNDO',
                       NULL, 1.00, '4.JPG',1 , GETDATE(),GETDATE())
					   
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (5, 3, 'FRUTILLA', 5.10, 300, 
                      'LA FRESA EN NATIVA DE TODAS LAS REGIONES TEMPLADAS DEL MUNDO  Y SE CULTIVAN EN GRANDES CANTIDADES ESTE FRUTO
                     ES EL RESULTADO  DE LA AGREGACION DE MUCHOS CARPELOS SECOS DIMINUTOS SOBRE UN RECEPTACULO PULPOSO DE COLOR ROJO',
                       NULL, 0.70, '5.JPG',1 , GETDATE(),GETDATE())
					   
					   
INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (6, 3, 'MORA', 5.05, 500, 
                      'EL FRUTO MADURO LLAMADO MORAES UN AGREPADO DE PEUEÑAS DRUPAS DE COLOR PÚRPURA OSCURO UNIDAS A UN RECEPTACULO
                      CÓNICO QUE SE SEPARA FÁCILMENTE DE LA PLANTA  ',
                       NULL, 0.70, '6.JPG',1 , GETDATE(),GETDATE())
					   

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (7, 3, 'PIÑA', 5.90, 100, 
                      'FAMILIA DE PLANTAS CON FLORES CARACTERIZADAS POR UNAS ESCAMAS FOLIARES EXCLUSIVAS QUE 
                    TIENEN LA PROPIEDAS DE RETENER AGUA Y POR FLORES REGULARES DE TRES PIEZAS CON MAS DE 2000 ESPECIES Y 46 GENEROS ',
                       NULL, 1.00, '7.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (8, 3, 'LIMON', 3.20, 100, 
                      'NOMBRE COMUN DE UN PEQUEÑO ARBOL ESPINOSO QUE PRODUCE EL FRUTO LLAMADO LIMON ESTE SE CULTIVA EN TODAS LAS REGIONES
                     TROPICALES Y SUBTROPICALES DEL MUNDO',
                       NULL, 1.15, '8.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (9, 3, 'BABACO', 2.10, 100, 
                      'ORIGINARIO DE ECUADOR  SE PRODUCE TODO EL AÑO Y CONTIENE VITAMINA C  Y SE PRODUCE EN TODAS LAS
                      REGIONES INTERANDINAS',
                       NULL, 1.15, '9.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (10, 3, 'MANGO', 3.10, 100, 
                      ' ES NATIVO DE INDIA CRECE HASTA UNOS Q5 M DE ALTURA Y FORMA NUMEROSAS RAMAS ALTAS Y ABIERTAS  RODEADO DE CUBIERTA LEÑOSA',
                       NULL, 2.15, '10.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (11, 3, 'SANDIA', 5.15, 100, 
                      'LAS SANDIAS SON MUY VARIABLES EN CUANTO A FORMA TAMAÑO Y MANCHAS DE CASCARA  HAY REINA FABIOLA SUGAR BABY Y PANOMIA',
                       NULL, 2.10, '11.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (12, 3, 'TOMATILLO', 2.20, 100, 
                      'ORIGINARIO DE SUDAMERICA COLOMBIA Y PERU TIENE VITAMINAS A B C E y K EN EL ECUADOR SE PRODUCE EN TODAS LAS PROVINCIAS DE LA REGION INTERANDINA',
                       NULL, 1.15, '12.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (13, 3, 'UVA', 1.15, 100, 
                      'LA DISPERSION DE LAS SEMILLAS POR LAS AVES EL VIENTO Y EL AGUA DIFUNDIO LA PLANTA HACIA EL OESTE ',
                       NULL, 1.15, '13.JPG',1 , GETDATE(),GETDATE())






INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (14, 3, 'BANANO', 3.20, 100, 
                      'NOMBRE COMUN DE UN GENERO TROPICAL DE PLANTAS HERBACEAS DE PORTE ARABOREO ORIGINARAS DEL SURESTE ASIATICO',
                       NULL, 2.10, '14.JPG',1 , GETDATE(),GETDATE())




INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (15, 3, 'MELON', 2.10, 100, 
                      'PERTENECEN A DOS ESPECIES DE ENREDADERAS RASTRERAS EN SUS VARIEDADES AMARILLO ORO TENDA DE INVIERNO ENTRE OTROS',
                       NULL, 1.15, '15.JPG',1 , GETDATE(),GETDATE())






INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (16, 3, 'MARACUYA', 3.10, 100, 
                      'ES UNA PLANTA TREPADORA DE LOS BOSQUES  LA FRUTA ES UNA BAYA DEL TAMAÑO DE UN HUEVO Y CONTIENE ABUNDANTES SEMILLAS ',
                       NULL, 2.15, '16.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (17, 3, 'NARANJILLA', 3.15, 100, 
                      'ES UN FRUTO REDONDO Y PEQUEÑO LAS HOJAS DE ESTE ARBUSTO ESTAN CUBIERTAS DE UNA VELLOSIDAD BLANQUECINA  LOS CENTROS DE PRODUCCION ESTAN EN PRYO TANDAPI LOJA Y ZAMORA',
                       NULL, 1.05, '17.JPG',1 , GETDATE(),GETDATE())





INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)
VALUES     (18, 3, 'PAPAYA', 4.45, 100, 
                      'ESTE SE DISTRIBUYE EN MEXICO  CENTROAMERICA  BRASIL Y OTRAS ZONAS TROPICALES ESTE LLEGA A MEDIR HASTA 8 METROS',
                       NULL, 1.15, '18.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (1, 4, 'ACER', 4.50, 100, 
                      'DE FAMILIA ACERACEAE PROVENIENTE DE CHINA Y JAPON NOMBRE COMUN ARCE PALMADO',
                       NULL, 0.10, '1.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (2, 4, ' ARCE', 5.50, 100, 
                      'CON TRATAMIENTO DE ABONO LAS PLANTAS DE ARCE CRECEN BASTANTAE',
                       NULL, 0.12, '2.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (3, 4, ' AZALEA', 4.50, 100, 
                      'PLANTA MAS HERMOSA A CULTIVAR UN HUERTO DEL ESTILO DE LOS BONSAI ESTE ES UN MIEMBRO DEL GENERO RODODENDRO',
                       NULL, 0.10, '3.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (4, 4, ' BUGANVILLEA', 3.50, 100, 
                      'SUS FLORES TIENE ALGUNAS PROPIEDADES MEDICINALES Y EN ALGUNOS PAISES SON UTILIZADAS COMO INFUSION',
                       NULL, 0.10, '4.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (5, 4, ' CALIANDRA', 3.50, 100, 
                      'PERFECCIONA EL MOLDEADO DE BONSAI ARTE DE ARBOLES DE ESTA PLANTA',
                       NULL, 0.10, '5.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (6, 4, ' CARMONA', 4.50, 100, 
                      ' ESTA ES UNA ESPECIE QUE EXIGE DEDICACION DEBIDO A SUS NECESIDADES DE CULTIVO SE NECESITA EXPERIENCIA EN SU CULTIVO',
                       NULL, 0.20, '6.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (7, 4, 'PALMATUM ', 5.50, 100, 
                      'BONSAI DE CUIDADO ESPECIAL  PARA SU CULTIVO',
                       NULL, 0.15, '7.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (8, 4, ' COPAL', 3.50, 100, 
                      'COPAL ARBOL DE LA ABUNDANCIA SEGUN SU TRONCO Y SUS HOJAS ',
                       NULL, 0.10, '8.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (9, 4, ' CYPRESS ', 3.00, 100, 
                      'BONSAI PARA TRABAJARLO DE DIFERNTE FORMA FACIL DE CULTIVA Y TRATAR',
                       NULL, 0.16, '9.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (10, 4, ' DIOSPYROS ', 3.50, 100, 
                      'CON ESTE BONSAI PODEMOS TRABAJAR EN TODOS LOS ESTILOS  Y DE FACIL CULTIVO ',
                       NULL, 0.10, '10.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (11, 4, ' FICUS ', 4.00, 100, 
                      'ESTE ES UNOS DE LOS BONSAIS MAS FACILES DE CULTIVASR EXIGE MUCHO MENOS QUE EL CARMONA ',
                       NULL, 0.15, '11.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (12, 4, ' HOKIDACHI ', 3.00, 100, 
                      'BONSAI DE SUELOS ALCALINOS DE HOJA ATRACTIVA',
                       NULL, 0.15, '12.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (13, 4, ' NAKA ', 2.00, 100, 
                      'HERMOSA ESPECIE DE PLANTA PARA CULTIVARLA Y LLEVARLA A BONSAI',
                       NULL, 0.20, '13.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (14, 4, ' OLIVO ', 1.50, 100, 
                      'ES ENDEMICO DEL MEDITERRANEO DE SUELOS ACIDO O ALCALINOS CRECE LENTAMENTE PERO VIGOROSAMENTE ',
                       NULL, 0.15, '14.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (15, 4, ' PENDULA ', 1.50, 100, 
                      'AUTOCTONA ORIGINARIA DE CASI TODA EUROPA OESTE DE SIBERIA  ARBOL DE HOJA CADUCA ATRACTIVA CORTEZA PLATEADA DE ADULTO Y HOJAS AMARILLAS',
                       NULL, 0.15, '15.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (16, 4, ' ZELKLARGE ', 1.50, 100, 
                      'BONSAI DE CULTIVO CUIDADOSO Y LENTO CRECIMIENTO',
                       NULL, 0.10, '16.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (17, 4, ' ZELKOVA ', 3.00, 100, 
                      'BONSAI HERMOSO DE CULTIVO CUIDADOSO CON UN TRONCO DURO Y HOJAS GRUESAS',
                       NULL, 0.05, '17.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (1, 5, ' MEDINILLA', 0.20, 100, 
                      ' ES UNA ESPECIE DE DIFICIL CULTIVO SIN EMBARGO SI LE OFRECEMOS TODOS LOS CUIDADOS  CRECERA CON UN COLORIDO SIN IGUAL',
                       NULL, 0.05, '1.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (2, 5, ' HELECHOS ', 0.50, 100, 
                      'SON UN GRUPO DE PLANTAS VASCULARES SON PLANTAS QUE CARECEN DE SEMILLAS Y SE REPRODUCEN POR ESPORAS',
                       NULL, 2.00, '2.JPG',1 , GETDATE(),GETDATE())




INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (3, 5, ' ORQUIDEAS', 2.00, 100, 
                      'TIENEN FLORES MUY GRANDES Y VISTOSAS PUEDEN VIVIR ENTRE CINCUENTA Y SETENTA AÑOS Y TRANSCURREN UNOS 4 AÑOS DESDE LA GERMINACION DE LA SEMILLA HATA LA PRIMERA FLOR',
                       NULL, 0.08, '3.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (4, 5, 'ALPINIA', 1.00, 100, 
                      'EXTREMADAMENTE FUERTE AGUANTA VIENTOS FUERTES INDIRECTOS TEMPERATURAS HATA 0 GRADOS REQUIERE SEMISOMBRA O SOMBRA HUMEDAD Y RIEGO ABUNDANTE EN VERANO',
                       NULL, 0.06, '4.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (5, 5, ' ANTURIOS ROJOS', 2.00, 100, 
                      'DE COLORES ROJOS BRILLANTES PONEN EN CONTRASTE MARAVILLOSAMENTE CON LAS HOJAS AMPLIAS CEROSAS DELICIOSAS SON DE ROBUSTAS HOJAS',
                       NULL, 0.05, '5.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (6, 5, ' AVE DEL PARAISO', 3.00, 100, 
                      'CARECE DE TRONCO Y EN SU LUGAR CONSTA DE VARIOS TALLOS HERBACEOS GRUESOS QUE NACEN VERTICALMENTE DE UN RIZOMA GRANDE SUBTERRANEO ',
                       NULL, 0.10, '6.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (7, 5, ' ANTHURIUM', 2.50, 100, 
                      'LORES EXOTICAS DE COLORES ROJO ROSADO BLANCO Y ANARANJADO ALCANZA UNA ALTURA DE UN METRO SON GURESAO Y CARNOSO',
                       NULL, 0.06, '7.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (8, 5, ' CICA REVOLUTA', 3.00, 100, 
                      'DE CONTRASTE MARAVILLOSO CON HOJAS AMPLIAS Y CEROSAS DE DIFERENTES COLORES ',
                       NULL, 0.09, '8.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (9, 5, ' PLATANO GUINEO', 4.00, 100, 
                      'PLANTAS HERBACEAS QUE PRODUCEN UN FRUTO LLAMADO BANANO ORIGINARIAS DEL SURESTE ASIATICO ',
                       NULL, 0.10, '9.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (10, 5, ' BOUGAINVILLEA', 2.00, 100, 
                      'ORIGINARIAS DE AMERICA DEL SUR  ESTA PLANTA ES CAPAZ DE RESISTIR TODOS LOS CLIMAS ESPECIALEMTNE LOS CALIDOS Y SECOS PRODUCE TODA GAMA DE COLORES EN SUS FLORES',
                       NULL, 0.05, '10.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (11, 5, ' DIEFFENBACHIA AMOENA', 2.00, 100, 
                      ' PLANTAS SE SEMILLA PEQUEÑA CAPAZ DE RESISTIR A TODOS LOS CLIMAS CALIDOS Y SECOS ORIGINARIA DE AMERIA DEL SUR',
                       NULL, 0.05, '11.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (1, 6, ' AGUACATE', 0.20, 100, 
                      'LA MISMA SEMILLA DE LA FRUTA NOS SIRVE PARA LA CREACION Y CULTIVACION DE ESTA PLANTA',
                       NULL, 0.05, '1.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (2, 6, ' ANIS', 0.50, 100, 
                      'SEMILLAS DE ANIS PARA INFUSIONES ',
                       NULL, 0.03, '2.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (3, 6, ' DURAZNO', 0.20, 100, 
                      'LA MISMA SEMILLA DE LA FRUTA SIRVE PARA LA CULTIVACION DE ESTA PLANTA CON UN PERIODO DE SECADO DE ESTA',
                       NULL, 0.05, '3.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (4, 6, ' GIRASOL', 0.50, 100, 
                      'SEMILLAS EXTRAIDAS DE LA MISMA PLANTA PARA SEMBRARLA',
                       NULL, 0.05, '4.JPG',1 , GETDATE(),GETDATE())

INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (5, 6, ' MANZANA', 0.20, 100, 
                      'SEMILLA DE LA FRUTA CON UN PERIODO DE SECADO PARA SEMBRARLA ',
                       NULL, 0.05, '5.JPG',1 , GETDATE(),GETDATE())



INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (6, 6, 'NARANJA', 0.50, 100, 
                      'SEMILLA EXTRAIDAS DE LA MISMA PLANTA FRUTAL CON PERIODO DE SECADO',
                       NULL, 0.06, '6.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (7, 6, 'SANDIA', 0.50, 100, 
                      'SEMILLA EXTRAIDA DE LA PLANTA FRUTAL',
                       NULL, 0.02, '7.JPG',1 , GETDATE(),GETDATE())


INSERT INTO SWVMMPRODUCTO04
                      (SWVM04PROD_ID, SWVM04CATE_ID, SWVM04PROD_NOMBRE, SWVM04PRECIO, SWVM04STOCK, SWVM04DESCRIPCION, SWVM04URL, SWVM04SIZE, SWVM04IMAGENAME, SWVM04PROV_ID, SWVM04FECHA_REGPRO, SWVM04FECHA_UPDATE)

VALUES     (8, 6, ' TOMATE', 0.80, 100, 
                      'SEMILLAS EXTRAIDA DE LA FRUTA CON PERIODO DE SECADO',
                       NULL, 0.05, '8.JPG',1 , GETDATE(),GETDATE())
