
--STORE PROCEDURE--
------CLIENTE----
CREATE PROCEDURE SP_INSERT_CLIENTE
	
	@SWVM02CLI_ID INT, 
	@SWVM02NOMBRE VARCHAR(50), 
	@SWVM02DIRECCION VARCHAR(45), 
	@SWVM02CIRUC VARCHAR(13), 
	@SWVM02PROVINCIA VARCHAR(30), 
	@SWVM02CIUDAD VARCHAR(30), 
	@SWVM02TELEFONO1 VARCHAR(10), 
	@SWVM02TELEFONO2 VARCHAR(10), 
	@SWVM02EMAIL VARCHAR(80),
	@SWVM02CLAVE VARCHAR(250),  
	@SWVM02ESTADO VARCHAR(1), 
	@SWVM02FECHA_REGC DATETIME,
	@SWVM02FECHA_UPDATE DATETIME
	
AS 
	INSERT INTO SWVMMCLIENTE02 	
	VALUES(
	@SWVM02CLI_ID, 
	@SWVM02NOMBRE, 
	@SWVM02DIRECCION, 
	@SWVM02CIRUC, 
	@SWVM02PROVINCIA, 
	@SWVM02CIUDAD, 
	@SWVM02TELEFONO1, 
	@SWVM02TELEFONO2, 
	@SWVM02EMAIL,
	@SWVM02CLAVE,  
	@SWVM02ESTADO, 
	@SWVM02FECHA_REGC,
	@SWVM02FECHA_UPDATE)

GO
	
	/*   **********************       */
	
	CREATE PROCEDURE SP_UPDATE_CLIENTE
	
    @SWVM02CLI_ID INT, 
	@SWVM02NOMBRE VARCHAR(50), 
	@SWVM02DIRECCION VARCHAR(45), 
	@SWVM02CIRUC VARCHAR(13), 
	@SWVM02PROVINCIA VARCHAR(30), 
	@SWVM02CIUDAD VARCHAR(30), 
	@SWVM02TELEFONO1 VARCHAR(10), 
	@SWVM02TELEFONO2 VARCHAR(10), 
	@SWVM02EMAIL VARCHAR(80),
	@SWVM02CLAVE VARCHAR(250),  
	@SWVM02ESTADO VARCHAR(1), 
	@SWVM02FECHA_UPDATE DATETIME
	
AS
		UPDATE SWVMMCLIENTE02
			SET			
			SWVM02NOMBRE= @SWVM02NOMBRE,
			SWVM02DIRECCION = @SWVM02DIRECCION , 
			SWVM02CIRUC = @SWVM02CIRUC, 
			SWVM02PROVINCIA = @SWVM02PROVINCIA, 
			SWVM02CIUDAD = @SWVM02CIUDAD , 
			SWVM02TELEFONO1 = @SWVM02TELEFONO1, 
			SWVM02TELEFONO2 = @SWVM02TELEFONO2 , 
			SWVM02EMAIL = @SWVM02EMAIL,
			SWVM02CLAVE = @SWVM02CLAVE,  
			SWVM02ESTADO = @SWVM02ESTADO, 
			SWVM02FECHA_UPDATE  = @SWVM02FECHA_UPDATE
			WHERE SWVM02CLI_ID=@SWVM02CLI_ID

GO
			
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_CLIENTE
	@SWVM02CLI_ID INT,
	@ERROR VARCHAR (5) OUTPUT 	
AS
    DECLARE @ERROR_VAR int 
	DELETE FROM SWVMMCLIENTE02
		WHERE (SWVM02CLI_ID=@SWVM02CLI_ID)
	SELECT @ERROR_VAR = @@ERROR
	
	IF (@ERROR_VAR <> 0)
			SET @ERROR = 'ERROR'
	ELSE 
	        SET @ERROR = 'GRABO'
			
GO		
			
----------USUARIO-----

CREATE PROCEDURE SP_INSERT_USUARIO
	@SWVM08USER_ID INT,
	@SWVM08NOMBRE VARCHAR(50), 
	@SWVM08DEPARTAMENTO VARCHAR(30), 
	@SWVM08CARGO VARCHAR(15), 
	@SWVM08EMAIL VARCHAR(80), 
	@SWVM08CLAVE VARCHAR(250),
	@SWVM08ESTADO VARCHAR(1),
	@SWVM08FECHA_REGU DATETIME,
	@SWVM08FECHA_UPDATE DATETIME 
AS 
	INSERT INTO SWVMMUSUARIO08 
	VALUES
	(	@SWVM08USER_ID,
		@SWVM08NOMBRE, 
		@SWVM08DEPARTAMENTO, 
		@SWVM08CARGO, 
		@SWVM08EMAIL, 
		@SWVM08CLAVE,
		@SWVM08ESTADO,
		@SWVM08FECHA_REGU,
		@SWVM08FECHA_UPDATE) 

GO
	
	/*   **********************       */
	
	CREATE PROCEDURE SP_UPDATE_USUARIO
	
	@SWVM08USER_ID INT,
	@SWVM08NOMBRE VARCHAR(50), 
	@SWVM08DEPARTAMENTO VARCHAR(30), 
	@SWVM08CARGO VARCHAR(15), 
	@SWVM08EMAIL VARCHAR(80), 
	@SWVM08CLAVE VARCHAR(250),
	@SWVM08ESTADO VARCHAR(1),	
	@SWVM08FECHA_UPDATE DATETIME 	
AS
		UPDATE SWVMMUSUARIO08
			SET			
			SWVM08NOMBRE=@SWVM08NOMBRE,
			SWVM08DEPARTAMENTO=@SWVM08DEPARTAMENTO,
			SWVM08CARGO=@SWVM08CARGO,
			SWVM08EMAIL=@SWVM08EMAIL, 			
			SWVM08CLAVE=@SWVM08CLAVE,
			SWVM08ESTADO=@SWVM08ESTADO, 			
			SWVM08FECHA_UPDATE=@SWVM08FECHA_UPDATE
			WHERE SWVM08USER_ID=@SWVM08USER_ID

GO
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_USUARIO
	@SWVM08USER_ID INT
AS
	DELETE FROM SWVMMUSUARIO08
		WHERE (SWVM08USER_ID=@SWVM08USER_ID)
			
GO
--------PRODUCTO-----------

CREATE PROCEDURE SP_INSERT_PRODUCTO
	@SWVM04PROD_ID INT,
	@SWVM04CATE_ID INT,
	@SWVM04PROD_NOMBRE VARCHAR(30), 
	@SWVM04PRECIO "MONEY",
	@SWVM04STOCK INT,
	@SWVM04DESCRIPCION VARCHAR(500),
	@SWVM04URL VARCHAR(120), 
	@SWVM04SIZE VARCHAR(10), 
	@SWVM04IMAGENAME VARCHAR(60), 
	@SWVM04PROV_ID INT,
	@SWVM04FECHA_REGPRO DATETIME,
	@SWVM04FECHA_UPDATE DATETIME
AS 
	INSERT INTO SWVMMPRODUCTO04 	
	VALUES
	(	@SWVM04PROD_ID, 
		@SWVM04CATE_ID, 
		@SWVM04PROD_NOMBRE,
		@SWVM04PRECIO,
		@SWVM04STOCK,
		@SWVM04DESCRIPCION,
		@SWVM04URL, 
		@SWVM04SIZE,
		@SWVM04IMAGENAME,
		@SWVM04PROV_ID,
		@SWVM04FECHA_REGPRO,
		@SWVM04FECHA_UPDATE)
GO

/*   **********************       */
	
	CREATE PROCEDURE SP_UPDATE_PRODUCTO
	
	@SWVM04PROD_ID INT,
	@SWVM04CATE_ID INT,
	@SWVM04PROD_NOMBRE VARCHAR(30), 
	@SWVM04PRECIO "MONEY",
	@SWVM04STOCK INT,
	@SWVM04DESCRIPCION VARCHAR(500),
	@SWVM04URL VARCHAR(120), 
	@SWVM04SIZE VARCHAR(10), 
	@SWVM04IMAGENAME VARCHAR(60), 
	@SWVM04PROV_ID INT,	
	@SWVM04FECHA_UPDATE DATETIME	
	
AS
		UPDATE SWVMMPRODUCTO04
			SET						
			SWVM04CATE_ID=@SWVM04CATE_ID,
			SWVM04PROD_NOMBRE=@SWVM04PROD_NOMBRE,
			SWVM04PRECIO=@SWVM04PRECIO,
			SWVM04STOCK=@SWVM04STOCK, 
			SWVM04DESCRIPCION=@SWVM04DESCRIPCION,
			SWVM04URL=@SWVM04URL,
			SWVM04SIZE=@SWVM04SIZE,
			SWVM04IMAGENAME=@SWVM04IMAGENAME,
			SWVM04PROV_ID=@SWVM04PROV_ID,
			SWVM04FECHA_UPDATE=@SWVM04FECHA_UPDATE
			WHERE (SWVM04PROD_ID=@SWVM04PROD_ID AND SWVM04CATE_ID=@SWVM04CATE_ID AND SWVM04PROV_ID=@SWVM04PROV_ID)

GO
			
/*   **********************       */


	CREATE PROCEDURE SP_DELETE_PRODUCTO
	@SWVM04PROD_ID INT,
	@SWVM04CATE_ID INT,
	@SWVM04PROV_ID INT,
	@ERROR VARCHAR (5) OUTPUT 	
AS
    DECLARE @ERROR_VAR int 
	DELETE FROM SWVMMPRODUCTO04
		WHERE (SWVM04PROD_ID=@SWVM04PROD_ID AND SWVM04CATE_ID=@SWVM04CATE_ID AND SWVM04PROV_ID=@SWVM04PROV_ID)
	SELECT @ERROR_VAR = @@ERROR
	
	IF (@ERROR_VAR <> 0)
			SET @ERROR = 'ERROR'
	ELSE 
	        SET @ERROR = 'GRABO'
			
			
GO


---------PROVEEDOR-------


CREATE PROCEDURE SP_INSERT_PROVEEDOR
	@SWVM01PROV_ID INT, 	
	@SWVM01NOM_EMPRESA VARCHAR(50), 
	@SWVM01NOM_CONTACTO VARCHAR(50), 
	@SWVM01CARGO_CONTACTO VARCHAR(20), 
	@SWVM01RUC VARCHAR(13), 
	@SWVM01DIRECCION VARCHAR(45), 
	@SWVM01TELEFONO1 VARCHAR(10), 
	@SWVM01TELEFONO2 VARCHAR(10), 
	@SWVM01PAIS VARCHAR(15), 
	@SWVM01PROVINCIA VARCHAR(30), 
	@SWVM01CIUDAD VARCHAR(30), 
	@SWVM01EMAIL VARCHAR(80),
	@SWVM01CLAVE VARCHAR(250),
	@SWVM01ESTADO VARCHAR(1), 
	@SWVM01FECHA_REGP DATETIME,
	@SWVM01FECHA_UPDATE DATETIME
AS 
	INSERT INTO SWVMMPROVEEDOR01 
	(	SWVM01PROV_ID, 
		SWVM01NOM_EMPRESA, 
		SWVM01NOM_CONTACTO,
		SWVM01CARGO_CONTACTO,
		SWVM01RUC,
		SWVM01DIRECCION,
		SWVM01TELEFONO1, 
		SWVM01TELEFONO2,
		SWVM01PAIS,
		SWVM01PROVINCIA,
		SWVM01CIUDAD,
		SWVM01EMAIL, 
		SWVM01CLAVE, 
		SWVM01ESTADO, 
		SWVM01FECHA_REGP, 
		SWVM01FECHA_UPDATE)	
	VALUES
	(	@SWVM01PROV_ID, 
		@SWVM01NOM_EMPRESA, 
		@SWVM01NOM_CONTACTO,
		@SWVM01CARGO_CONTACTO,
		@SWVM01RUC,
		@SWVM01DIRECCION,
		@SWVM01TELEFONO1, 
		@SWVM01TELEFONO2,
		@SWVM01PAIS,
		@SWVM01PROVINCIA,
		@SWVM01CIUDAD,
		@SWVM01EMAIL, 
		@SWVM01CLAVE, 
		@SWVM01ESTADO, 
		@SWVM01FECHA_REGP, 
		@SWVM01FECHA_UPDATE)
	

GO
	/*   **********************       */
	
	CREATE PROCEDURE SP_UPDATE_PROVEEDOR
	
	@SWVM01PROV_ID INT, 	
	@SWVM01NOM_EMPRESA VARCHAR(50), 
	@SWVM01NOM_CONTACTO VARCHAR(50), 
	@SWVM01CARGO_CONTACTO VARCHAR(20), 
	@SWVM01RUC VARCHAR(13), 
	@SWVM01DIRECCION VARCHAR(45), 
	@SWVM01TELEFONO1 VARCHAR(10), 
	@SWVM01TELEFONO2 VARCHAR(10), 
	@SWVM01PAIS VARCHAR(15), 
	@SWVM01PROVINCIA VARCHAR(30), 
	@SWVM01CIUDAD VARCHAR(30), 
	@SWVM01EMAIL VARCHAR(80),
	@SWVM01CLAVE VARCHAR(250),
	@SWVM01ESTADO VARCHAR(1), 	
	@SWVM01FECHA_UPDATE DATETIME	
	
AS
		UPDATE SWVMMPROVEEDOR01
			SET			
			SWVM01NOM_EMPRESA=@SWVM01NOM_EMPRESA,
			SWVM01NOM_CONTACTO=@SWVM01NOM_CONTACTO,
			SWVM01CARGO_CONTACTO=@SWVM01CARGO_CONTACTO,
			SWVM01RUC=@SWVM01RUC,
			SWVM01DIRECCION=@SWVM01DIRECCION, 
			SWVM01TELEFONO1=@SWVM01TELEFONO1,
			SWVM01TELEFONO2=@SWVM01TELEFONO2,
			SWVM01PAIS=@SWVM01PAIS,
			SWVM01PROVINCIA=@SWVM01PROVINCIA,
			SWVM01CIUDAD=@SWVM01CIUDAD,
			SWVM01EMAIL=@SWVM01EMAIL,
			SWVM01CLAVE=@SWVM01CLAVE,
			SWVM01ESTADO=@SWVM01ESTADO, 
			SWVM01FECHA_UPDATE=@SWVM01FECHA_UPDATE 
			WHERE SWVM01PROV_ID=@SWVM01PROV_ID

GO
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_PROVEEDOR
	@SWVM01PROV_ID INT,
	@ERROR VARCHAR (5) OUTPUT 	
AS
    DECLARE @ERROR_VAR int 
	DELETE FROM SWVMMPROVEEDOR01
		WHERE (SWVM01PROV_ID=@SWVM01PROV_ID)
	SELECT @ERROR_VAR = @@ERROR
	
	IF (@ERROR_VAR <> 0)
			SET @ERROR = 'ERROR'
	ELSE 
	        SET @ERROR = 'GRABO'
			
			
GO

-----COTIZA--------


CREATE PROCEDURE SP_INSERT_CABCOTI
	@SWVM06COTI_ID INT, 
	@SWVM06FECHA DATETIME,
	@SWVM06CLI_ID INT, 
	@SWVM06TOTAL "MONEY",
	@SWVM06ESTADO VARCHAR(1),
	@SWVM06FECHA_UPDATE DATETIME
AS 
	INSERT INTO SWVMCCAB_COTI06 
	VALUES
	(	@SWVM06COTI_ID, 
		@SWVM06FECHA,
		@SWVM06CLI_ID, 
		@SWVM06TOTAL,
		@SWVM06ESTADO,
		@SWVM06FECHA_UPDATE)

GO
	
	/*   **********************       */
	
CREATE PROCEDURE SP_INSERT_DETCOTI
	@SWVM07COTI_ID INT, 
	@SWVM07PROD_ID INT, 
	@SWVM07CATE_ID INT, 
	@SWVM07CANTIDAD INT, 
	@SWVM07PRECIO "MONEY",
	@SWVM07SUBTOTAL "MONEY",
	@SWVM07IVA "MONEY",
	@SWVM07PROV_ID INT
AS 
	INSERT INTO SWVMDDET_COTI07 
	VALUES
	(	@SWVM07COTI_ID, 
		@SWVM07PROD_ID,
		@SWVM07CATE_ID, 
		@SWVM07CANTIDAD,
		@SWVM07PRECIO,
		@SWVM07SUBTOTAL,
		@SWVM07IVA,
		@SWVM07PROV_ID)

GO
	
	/*   **********************       */
	
CREATE PROCEDURE SP_UPDATE_CABCOTI
	@SWVM06COTI_ID INT,
	@SWVM06ESTADO VARCHAR(1),
	@SWVM06FECHA_UPDATE DATETIME
AS
		UPDATE SWVMCCAB_COTI06
			SET			
			SWVM06ESTADO=@SWVM06ESTADO,
			SWVM06FECHA_UPDATE=@SWVM06FECHA_UPDATE
			WHERE SWVM06COTI_ID=@SWVM06COTI_ID

GO
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_CABCOTI
	@SWVM06COTI_ID INT
AS
	DELETE FROM SWVMCCAB_COTI06
		WHERE (SWVM06COTI_ID=@SWVM06COTI_ID)

GO
		
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_DETCOTI
	@SWVM07COTI_ID INT
AS
	DELETE FROM SWVMDDET_COTI07
		WHERE (SWVM07COTI_ID=@SWVM07COTI_ID)
		
GO