CREATE PROCEDURE SP_INSERT_CLIENTE
	@SWVM02CLI_ID INT, 
	@SWVM02NOMBRE VARCHAR(50), 
	@SWVM02DIRECCION VARCHAR(45), 
	@SWVM02CIRUC VARCHAR(13), 
	@SWVM02PROVINCIA VARCHAR(30), 
	@SWVM02CIUDAD VARCHAR(30), 
	@SWVM02TELEFONO1 VARCHAR(10), 
	@SWVM02TELEFONO2 VARCHAR(10), 
	@SWVM02EMAIL VARCHAR(80),
	@SWVM02CLAVE VARCHAR(250),  
	@SWVM02ESTADO VARCHAR(1), 
	@SWVM02FECHA_REGC DATETIME,
	@SWVM02FECHA_UPDATE DATETIME
	
AS 
	INSERT INTO SWVMMCLIENTE02 
	(	SWVM02CLI_ID, 
		SWVM02NOMBRE, 
		SWVM02DIRECCION, 
		SWVM02CIRUC, 
		SWVM02PROVINCIA, 
		SWVM02CIUDAD, 
		SWVM02TELEFONO1, 
		SWVM02TELEFONO2, 
		SWVM02EMAIL, 
		SWVM02CLAVE, 
		SWVM02ESTADO, 
		SWVM02FECHA_REGC, 
		SWVM02FECHA_UPDATE)	
	VALUES
	(	@SWVM02CLI_ID, 
		@SWVM02NOMBRE, 
		@SWVM02DIRECCION, 
		@SWVM02CIRUC, 
		@SWVM02PROVINCIA, 
		@SWVM02CIUDAD, 
		@SWVM02TELEFONO1, 
		@SWVM02TELEFONO2, 
		@SWVM02EMAIL, 
		@SWVM02CLAVE, 
		@SWVM02ESTADO, 
		@SWVM02FECHA_REGC, 
		@SWVM02FECHA_UPDATE)	
	
	/*   **********************       */
	
	CREATE PROCEDURE SP_UPDATE_USUARIO
	@USER_ID INT, 
	@NOMBRE VARCHAR(50),
	@DEPARTAMENTO VARCHAR(30),
	@CARGO VARCHAR(15),
	@ESTADO VARCHAR(1), 
	@CLAVE VARCHAR(250), 
	@EMAIL VARCHAR(80), 
	@FECHA_UPDATE DATETIME
AS
		UPDATE USUARIO
			SET			
			NOMBRE=@NOMBRE,
			DEPARTAMENTO=@DEPARTAMENTO,
			CARGO=@CARGO,
			ESTADO=@ESTADO, 
			CLAVE=@CLAVE, 
			EMAIL=@EMAIL, 
			FECHA_UPDATE=@FECHA_UPDATE
			WHERE USER_ID=@USER_ID
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_USUARIO
	@USER_ID INT
AS
	DELETE FROM USUARIO
		WHERE (USER_ID=@USER_ID)
			