CREATE PROCEDURE SP_INSERT_CABCOTI
	@SWVM06COTI_ID INT, 
	@SWVM06FECHA DATETIME,
	@SWVM06CLI_ID INT, 
	@SWVM06TOTAL "MONEY",
	@SWVM06ESTADO VARCHAR(1),
	@SWVM06FECHA_UPDATE DATETIME
AS 
	INSERT INTO SWVMCCAB_COTI06 
	VALUES
	(	@SWVM06COTI_ID, 
		@SWVM06FECHA,
		@SWVM06CLI_ID, 
		@SWVM06TOTAL,
		@SWVM06ESTADO,
		@SWVM06FECHA_UPDATE)
	
	/*   **********************       */
	
CREATE PROCEDURE SP_INSERT_DETCOTI
	@SWVM07COTI_ID INT, 
	@SWVM07PROD_ID INT, 
	@SWVM07CATE_ID INT, 
	@SWVM07CANTIDAD INT, 
	@SWVM07PRECIO "MONEY",
	@SWVM07SUBTOTAL "MONEY",
	@SWVM07IVA "MONEY",
	@SWVM07PROV_ID
AS 
	INSERT INTO SWVMDDET_COTI07 
	VALUES
	(	@SWVM07COTI_ID, 
		@SWVM07PROD_ID,
		@SWVM07CATE_ID, 
		@SWVM07CANTIDAD,
		@SWVM07PRECIO,
		@SWVM07SUBTOTAL,
		@SWVM07IVA,
		@SWVM07PROV_ID)
	
	/*   **********************       */
	
CREATE PROCEDURE SP_UPDATE_CABCOTI
	@SWVM06COTI_ID INT,
	@SWVM06ESTADO VARCHAR(1),
	@SWVM06FECHA_UPDATE DATETIME
AS
		UPDATE SWVMCCAB_COTI06
			SET			
			SWVM06ESTADO=@SWVM06ESTADO,
			SWVM06FECHA_UPDATE=@SWVM06FECHA_UPDATE
			WHERE SWVM06COTI_ID=@SWVM06COTI_ID
			
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_CABCOTI
	@SWVM06COTI_ID INT
AS
	DELETE FROM SWVMCCAB_COTI06
		WHERE (SWVM06COTI_ID=@SWVM06COTI_ID)
		
/*   **********************       */

	CREATE PROCEDURE SP_DELETE_DETCOTI
	@SWVM07COTI_ID INT
AS
	DELETE FROM SWVMDDET_COTI07
		WHERE (SWVM07COTI_ID=@SWVM07COTI_ID)